[tool.black]
--line-length = 120

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 120
multi_line_output = 3

# [tool.flake8]
# max-line-length = 120
# ignore = "E203,E501,W503,W504"

[tool.pycln]
all = true