py_binary(
  name="model",
  srcs = ["model.py"],
  deps = [],
  visibility = ["//visibility:public"]
)

py_binary(
  name="losses",
  srcs = ["losses.py"],
  deps = [],
  visibility = ["//visibility:public"]
)

py_binary(
  name="metrics",
  srcs = ["metrics.py"],
  deps = [],
  visibility = ["//visibility:public"]
)
