py_binary(
  name="dataloader",
  srcs = ["dataloader.py"],
  deps = ["//python/model:losses"],
  visibility = ["//visibility:public"]
)
py_binary(
  name="utils",
  srcs = ["utils.py"],
  deps = [],
  visibility = ["//visibility:public"]
)
